<?php
/**
 * Suno REST API Connection adapter.
 *
 * @package WorldGraph
 */

namespace WorldGraph\Utils;

use WP_Error;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/** SunoAPI.org asynchronous music and lyrics client. */
class Suno_API {

	/** Default Suno API origin. */
	const ENDPOINT = 'https://api.sunoapi.org';

	/** HTTP timeout in seconds. */
	const TIMEOUT = 60;

	/** Music models accepted by the Suno REST API. */
	const MODELS = [ 'V4', 'V4_5', 'V4_5PLUS', 'V4_5ALL', 'V5', 'V5_5' ];

	/**
	 * Test an unsaved REST configuration by requesting its credit balance.
	 *
	 * @param string $endpoint             Suno API origin.
	 * @param string $credential_reference API key or env:// reference.
	 * @return array|WP_Error
	 */
	public static function test_configuration( string $endpoint, string $credential_reference ) {
		return self::credits_for( $endpoint, $credential_reference );
	}

	/**
	 * Return the remaining credits for a saved Suno Connection.
	 *
	 * @param int $connection_id Connection post ID.
	 * @return array|WP_Error
	 */
	public static function credits( int $connection_id ) {
		$connection = self::connection( $connection_id );
		if ( is_wp_error( $connection ) ) {
			return $connection;
		}

		return self::credits_for(
			(string) ( $connection['endpoint_url'] ?? self::ENDPOINT ),
			(string) ( $connection['credential_reference'] ?? '' )
		);
	}

	/** Alias used by Connection health checks. */
	public static function health( int $connection_id ) {
		return self::credits( $connection_id );
	}

	/**
	 * Submit one API-backed Suno Template.
	 *
	 * Supported references are api:generate, api:generate-custom, and
	 * api:lyrics. The callback URL is always generated by World Graph Studio;
	 * callers cannot redirect provider callbacks to an arbitrary URL.
	 *
	 * @param string $template      Transport-specific Template reference.
	 * @param string $prompt        Music description, lyrics, or lyrics brief.
	 * @param array  $parameters    Provider input values.
	 * @param int    $connection_id Connection post ID.
	 * @return array|WP_Error
	 */
	public static function run_template( string $template, string $prompt, array $parameters, int $connection_id = 0 ) {
		$connection = self::connection( $connection_id );
		if ( is_wp_error( $connection ) ) {
			return $connection;
		}

		$template = strtolower( trim( $template ) );
		if ( ! in_array( $template, [ 'api:generate', 'api:generate-custom', 'api:lyrics' ], true ) ) {
			return new WP_Error( 'suno_api_template_invalid', __( 'The Suno Template has an unsupported REST transport reference.', 'worldgraph' ) );
		}

		$text = trim( wp_strip_all_tags( $prompt ) );
		if ( 'api:lyrics' === $template ) {
			if ( '' === $text ) {
				return new WP_Error( 'suno_api_prompt_missing', __( 'Enter a description of the lyrics to generate.', 'worldgraph' ) );
			}

			$body = [
				'prompt'      => $text,
				'callBackUrl' => self::callback_url( $connection_id ),
			];
			$result = self::request( $connection, 'POST', '/api/v1/lyrics', $body );
			return is_wp_error( $result ) ? $result : self::normalize_result( $result, $template );
		}

		$model = trim( (string) ( $parameters['model'] ?? '' ) );
		if ( '' === $model ) {
			$model = trim( (string) ( $connection['model'] ?? '' ) );
		}
		$model = strtoupper( '' !== $model ? $model : 'V5' );
		if ( ! in_array( $model, self::MODELS, true ) ) {
			return new WP_Error( 'suno_api_model_invalid', __( 'Select a model supported by the Suno REST API.', 'worldgraph' ) );
		}
		if ( ! self::model_is_allowed( $connection, $model ) ) {
			return new WP_Error( 'suno_api_model_not_allowed', __( 'That Suno model is not allowed by the selected Connection.', 'worldgraph' ) );
		}

		$instrumental = rest_sanitize_boolean( $parameters['instrumental'] ?? false );
		$body         = [
			'customMode'  => 'api:generate-custom' === $template,
			'instrumental' => $instrumental,
			'model'        => $model,
			'callBackUrl'  => self::callback_url( $connection_id ),
		];

		if ( 'api:generate' === $template ) {
			if ( '' === $text ) {
				return new WP_Error( 'suno_api_prompt_missing', __( 'Enter a description of the music to generate.', 'worldgraph' ) );
			}
			$body['prompt'] = $text;
		} else {
			$style = trim( sanitize_text_field( (string) ( $parameters['style'] ?? '' ) ) );
			$title = trim( sanitize_text_field( (string) ( $parameters['title'] ?? '' ) ) );
			if ( '' === $style || '' === $title ) {
				return new WP_Error( 'suno_api_custom_fields_missing', __( 'Custom Suno generation requires both a style and a title.', 'worldgraph' ) );
			}
			if ( ! $instrumental && '' === $text ) {
				return new WP_Error( 'suno_api_lyrics_missing', __( 'Custom vocal music requires lyrics in the generation prompt.', 'worldgraph' ) );
			}

			$body['style'] = $style;
			$body['title'] = $title;
			if ( '' !== $text ) {
				$body['prompt'] = $text;
			}
		}

		$body = self::copy_optional_music_parameters( $parameters, $body );
		$result = self::request( $connection, 'POST', '/api/v1/generate', $body );
		return is_wp_error( $result ) ? $result : self::normalize_result( $result, $template );
	}

	/**
	 * Poll a Suno REST task.
	 *
	 * @param string $job_id        Suno task ID.
	 * @param int    $connection_id Connection post ID.
	 * @param string $template      Template reference used to select the record endpoint.
	 * @return array|WP_Error
	 */
	public static function get_job_status( string $job_id, int $connection_id = 0, string $template = '' ) {
		$job_id = trim( $job_id );
		if ( '' === $job_id ) {
			return new WP_Error( 'suno_api_job_id_missing', __( 'The Suno generation job has no task ID.', 'worldgraph' ) );
		}

		$connection = self::connection( $connection_id );
		if ( is_wp_error( $connection ) ) {
			return $connection;
		}

		$path   = 'api:lyrics' === strtolower( trim( $template ) ) ? '/api/v1/lyrics/record-info' : '/api/v1/generate/record-info';
		$result = self::request( $connection, 'GET', $path, [], [ 'taskId' => $job_id ] );
		return is_wp_error( $result ) ? $result : self::normalize_result( $result, $template );
	}

	/**
	 * Build the mandatory public callback URL for a saved Connection.
	 *
	 * @param int $connection_id Connection post ID.
	 * @return string
	 */
	public static function callback_url( int $connection_id ): string {
		$connection_id = absint( $connection_id );
		return add_query_arg(
			[
				'connection_id' => $connection_id,
				'token'         => self::callback_token( $connection_id ),
			],
			rest_url( 'worldgraph/v1/generation/suno-callback' )
		);
	}

	/**
	 * Return the stable WP-salt HMAC used to authenticate a Suno callback.
	 *
	 * @param int $connection_id Connection post ID.
	 * @return string
	 */
	public static function callback_token( int $connection_id ): string {
		return hash_hmac( 'sha256', 'worldgraph:suno:' . absint( $connection_id ), wp_salt( 'auth' ) );
	}

	/** Verify a token supplied to the public Suno callback route. */
	public static function verify_callback_token( int $connection_id, string $token ): bool {
		$token = trim( $token );
		return '' !== $token && hash_equals( self::callback_token( $connection_id ), $token );
	}

	/**
	 * Normalize a Suno REST submission, poll, or callback payload.
	 *
	 * Final music records are nested beneath items. Each record deliberately
	 * carries url and audio_url so the generic media importer can discover all
	 * final tracks while retaining Suno metadata.
	 *
	 * @param array  $payload  Decoded provider response.
	 * @param string $template Optional Template reference.
	 * @return array
	 */
	public static function normalize_result( array $payload, string $template = '' ): array {
		$data       = is_array( $payload['data'] ?? null ) ? $payload['data'] : $payload;
		$job_id     = self::first_scalar( $data, [ 'taskId', 'task_id' ] );
		$raw_status = self::first_scalar( $data, [ 'status', 'state' ] );
		$status     = self::normalize_status( $raw_status );
		$type       = strtoupper( self::first_scalar( $data, [ 'type' ] ) );
		$is_lyrics  = 'api:lyrics' === strtolower( trim( $template ) ) || 'LYRICS' === $type;

		$result = [
			'job_id'    => $job_id,
			'status'    => $status,
			'transport' => 'api',
		];
		if ( '' !== $raw_status ) {
			$result['provider_status'] = $raw_status;
		}
		if ( '' !== $type ) {
			$result['type'] = $type;
		}

		$error_message = self::first_scalar( $data, [ 'errorMessage', 'error_message' ] );
		if ( '' !== $error_message ) {
			$result['error'] = $error_message;
		}

		if ( 'completed' === $status ) {
			$items = self::result_items( $data, $is_lyrics );
			if ( ! empty( $items ) ) {
				$result['items'] = $items;
			}
		}

		return $result;
	}

	/** Map Suno task states onto World Graph Studio generation states. */
	public static function normalize_status( string $status ): string {
		$status = strtoupper( str_replace( [ ' ', '-' ], '_', trim( $status ) ) );
		if ( in_array( $status, [ 'SUCCESS', 'COMPLETED', 'COMPLETE', 'SUCCEEDED' ], true ) ) {
			return 'completed';
		}
		if ( in_array( $status, [ 'CANCELLED', 'CANCELED' ], true ) ) {
			return 'cancelled';
		}
		if ( in_array( $status, [ 'FAILED', 'ERROR', 'CREATE_TASK_FAILED', 'GENERATE_AUDIO_FAILED', 'GENERATE_LYRICS_FAILED', 'CALLBACK_EXCEPTION', 'SENSITIVE_WORD_ERROR' ], true ) ) {
			return 'failed';
		}

		return 'submitted';
	}

	/** Whether a model is permitted by the Connection's optional allowlist. */
	public static function model_is_allowed( array $connection, string $model ): bool {
		$raw = trim( (string) ( $connection['model_access'] ?? '' ) );
		if ( '' === $raw ) {
			return true;
		}

		$allowed  = json_decode( $raw, true );
		$canonical = self::canonical_model( $model );
		if ( ! is_array( $allowed ) || '' === $canonical ) {
			return false;
		}

		foreach ( $allowed as $candidate ) {
			if ( is_scalar( $candidate ) && $canonical === self::canonical_model( (string) $candidate ) ) {
				return true;
			}
		}

		return false;
	}

	/** Copy documented optional camelCase fields while preserving JSON types. */
	private static function copy_optional_music_parameters( array $parameters, array $body ): array {
		foreach ( [ 'personaId', 'negativeTags' ] as $key ) {
			if ( isset( $parameters[ $key ] ) && '' !== trim( (string) $parameters[ $key ] ) ) {
				$body[ $key ] = sanitize_text_field( (string) $parameters[ $key ] );
			}
		}

		if ( isset( $parameters['personaModel'] ) && in_array( $parameters['personaModel'], [ 'style_persona', 'voice_persona' ], true ) ) {
			$body['personaModel'] = (string) $parameters['personaModel'];
		}
		if ( isset( $parameters['vocalGender'] ) && in_array( $parameters['vocalGender'], [ 'm', 'f' ], true ) ) {
			$body['vocalGender'] = (string) $parameters['vocalGender'];
		}
		if ( isset( $parameters['duration'] ) ) {
			$body['duration'] = (int) $parameters['duration'];
		}
		foreach ( [ 'styleWeight', 'weirdnessConstraint', 'audioWeight' ] as $key ) {
			if ( isset( $parameters[ $key ] ) && is_numeric( $parameters[ $key ] ) ) {
				$body[ $key ] = (float) $parameters[ $key ];
			}
		}

		return $body;
	}

	/** Request the authenticated credit balance without a saved Connection. */
	private static function credits_for( string $endpoint, string $credential_reference ) {
		$result = self::request_to( $endpoint, $credential_reference, 'GET', '/api/v1/generate/credit' );
		if ( is_wp_error( $result ) ) {
			return $result;
		}

		return [
			'status'  => 'available',
			'credits' => is_numeric( $result['data'] ?? null ) ? (float) $result['data'] : $result['data'] ?? null,
		];
	}

	/** Perform one request for a saved Connection. */
	private static function request( array $connection, string $method, string $path, array $body = [], array $query = [] ) {
		return self::request_to(
			(string) ( $connection['endpoint_url'] ?? self::ENDPOINT ),
			(string) ( $connection['credential_reference'] ?? '' ),
			$method,
			$path,
			$body,
			$query
		);
	}

	/** Perform one authenticated JSON request and validate the API envelope. */
	private static function request_to( string $endpoint, string $credential_reference, string $method, string $path, array $body = [], array $query = [] ) {
		$headers = self::headers( $credential_reference );
		if ( is_wp_error( $headers ) ) {
			return $headers;
		}

		$url = self::api_root( $endpoint ) . $path;
		if ( ! empty( $query ) ) {
			$url = add_query_arg( $query, $url );
		}

		$args = [
			'timeout' => self::TIMEOUT,
			'headers' => $headers,
		];
		if ( 'POST' === $method ) {
			$args['body'] = wp_json_encode( $body );
			$response     = wp_remote_post( $url, $args );
		} else {
			$response = wp_remote_get( $url, $args );
		}

		if ( is_wp_error( $response ) ) {
			return new WP_Error( 'suno_api_unreachable', $response->get_error_message() );
		}

		$http_code = wp_remote_retrieve_response_code( $response );
		$raw       = (string) wp_remote_retrieve_body( $response );
		$decoded   = json_decode( $raw, true );
		if ( $http_code < 200 || $http_code >= 300 ) {
			return new WP_Error( 'suno_api_request_failed', self::error_message( $decoded, $http_code ), [ 'status' => $http_code ] );
		}
		if ( ! is_array( $decoded ) ) {
			return new WP_Error( 'suno_api_invalid_response', __( 'Suno returned invalid JSON.', 'worldgraph' ) );
		}
		if ( isset( $decoded['code'] ) && 200 !== (int) $decoded['code'] ) {
			return new WP_Error( 'suno_api_request_failed', self::error_message( $decoded, (int) $decoded['code'] ), [ 'status' => (int) $decoded['code'] ] );
		}

		return $decoded;
	}

	/** Build authenticated Suno REST headers. */
	private static function headers( string $credential_reference ) {
		$key = self::resolve_credential( $credential_reference );
		if ( '' === $key ) {
			return new WP_Error( 'suno_api_credential_missing', __( 'Set a Suno API key or env://SUNO_API_KEY reference on this Connection.', 'worldgraph' ) );
		}

		return [
			'Accept'        => 'application/json',
			'Authorization' => 'Bearer ' . $key,
			'Content-Type'  => 'application/json',
		];
	}

	/** Resolve and validate one saved Suno Connection. */
	private static function connection( int $connection_id ) {
		$connection = Connection_Repository::get( $connection_id );
		if ( ! is_array( $connection ) || 'suno' !== ( $connection['provider_type'] ?? '' ) ) {
			return new WP_Error( 'suno_api_connection_invalid', __( 'The selected Connection is not a Suno Connection.', 'worldgraph' ) );
		}

		return $connection;
	}

	/** Resolve a literal key or an env:// environment-variable reference. */
	private static function resolve_credential( string $reference ): string {
		$reference = trim( $reference );
		if ( 0 === strpos( $reference, 'env://' ) ) {
			$name = substr( $reference, 6 );
			if ( ! preg_match( '/^[A-Z_][A-Z0-9_]*$/', $name ) ) {
				return '';
			}
			$value = getenv( $name );
			return false === $value ? '' : trim( (string) $value );
		}

		return $reference;
	}

	/** Normalize a configured URL to the Suno API origin. */
	private static function api_root( string $endpoint ): string {
		$endpoint = untrailingslashit( esc_url_raw( $endpoint ?: self::ENDPOINT ) );
		return (string) preg_replace( '#/api(?:/v1)?$#', '', $endpoint );
	}

	/** Normalize REST and chirp aliases to one allowlist comparison value. */
	private static function canonical_model( string $model ): string {
		$model = strtoupper( trim( $model ) );
		$aliases = [
			'CHIRP-V4'          => 'V4',
			'CHIRP-V4-5'        => 'V4_5',
			'CHIRP-V4-5-PLUS'   => 'V4_5_PLUS_FAMILY',
			'V4_5PLUS'          => 'V4_5_PLUS_FAMILY',
			'V4_5ALL'           => 'V4_5_PLUS_FAMILY',
			'CHIRP-V5'          => 'V5',
			'CHIRP-V5-5'        => 'V5_5',
		];

		return $aliases[ $model ] ?? ( in_array( $model, self::MODELS, true ) ? $model : '' );
	}

	/** Extract a provider error without exposing credentials or response dumps. */
	private static function error_message( $decoded, int $code ): string {
		$message = is_array( $decoded ) ? ( $decoded['msg'] ?? $decoded['message'] ?? $decoded['error']['message'] ?? '' ) : '';
		return is_string( $message ) && '' !== trim( $message ) ? $message : sprintf( 'Suno returned code %d.', $code );
	}

	/** Return the first scalar value found beneath common response wrappers. */
	private static function first_scalar( array $data, array $keys ): string {
		foreach ( $keys as $key ) {
			if ( isset( $data[ $key ] ) && is_scalar( $data[ $key ] ) ) {
				return (string) $data[ $key ];
			}
		}
		foreach ( [ 'response', 'data' ] as $wrapper ) {
			if ( is_array( $data[ $wrapper ] ?? null ) ) {
				$value = self::first_scalar( $data[ $wrapper ], $keys );
				if ( '' !== $value ) {
					return $value;
				}
			}
		}

		return '';
	}

	/** Whether an array uses zero-based consecutive integer keys. */
	private static function is_list( array $value ): bool {
		return $value === array_values( $value );
	}

	/** Normalize all final music tracks or lyrics variants. */
	private static function result_items( array $data, bool $is_lyrics ): array {
		$candidates = [
			$data['response']['sunoData'] ?? null,
			$data['response']['data'] ?? null,
			$data['sunoData'] ?? null,
			$data['data'] ?? null,
		];
		$records = [];
		foreach ( $candidates as $candidate ) {
			if ( is_array( $candidate ) && self::is_list( $candidate ) ) {
				$records = $candidate;
				break;
			}
		}

		$items = [];
		foreach ( $records as $record ) {
			if ( ! is_array( $record ) ) {
				continue;
			}
			if ( $is_lyrics || isset( $record['text'] ) ) {
				$text = trim( (string) ( $record['text'] ?? '' ) );
				if ( '' !== $text ) {
					$items[] = [
						'text'   => $text,
						'title'  => sanitize_text_field( (string) ( $record['title'] ?? '' ) ),
						'status' => sanitize_key( (string) ( $record['status'] ?? 'complete' ) ),
					];
				}
				continue;
			}

			$audio_url = (string) ( $record['audioUrl'] ?? $record['audio_url'] ?? '' );
			if ( ! filter_var( $audio_url, FILTER_VALIDATE_URL ) ) {
				continue;
			}
			$item = [
				'url'       => $audio_url,
				'audio_url' => $audio_url,
			];
			$image_url = (string) ( $record['imageUrl'] ?? $record['image_url'] ?? '' );
			if ( filter_var( $image_url, FILTER_VALIDATE_URL ) ) {
				$item['cover_image_url'] = $image_url;
			}
			foreach ( [ 'id', 'title', 'prompt', 'tags', 'duration', 'modelName', 'model_name', 'createTime', 'created_at' ] as $key ) {
				if ( isset( $record[ $key ] ) && is_scalar( $record[ $key ] ) ) {
					$item[ $key ] = $record[ $key ];
				}
			}
			$items[] = $item;
		}

		return $items;
	}
}
